name: Python CI Pipeline

# 1. The Trigger (When should this run?)
on:
  push:
    branches:
      - main
      - master

# 2. The Jobs (What should we do?)
jobs:
  test-math:
    # 3. The Runner (Where should this run?)
    runs-on: ubuntu-latest

    # 4. The Steps (The robotic arms)
    steps:
      - name: 📥 Download the code from Git
        uses: actions/checkout@v3

      - name: 🐍 Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run the math test
        run: python calculator.py
# 2. THE CD PHASE (Packaging)
  build-and-push:
    # Wait for the tests to pass before building!
    needs: test-math 
    runs-on: ubuntu-latest
    steps:
      - name: Download the code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Replace YOUR_DOCKER_USERNAME below with your actual username!
          tags: YOUR_DOCKER_USERNAME/my-calculator:latest
